### ISSUE TITLE
overflow: sroll

### ISSUE THREAD

**Issue by SamSlotemaker** [Triggzs/blokweb#2]
als je de li's in bestellers een min-width geeft, worden ze groter dan de pagina, met overflow:scroll op de container (ul) kun je dan aangeven dat je er tussen kunt scrollen, op die manier heb je heel simpel de carousel van de nike site nagemaakt. 

```css
.bestellers {
  overflow: scroll
}

.bestellers li {
  min-width: 50vw;
}
```
